### ISSUE TITLE
Latex Formulas Failed to be Rendered 

### ISSUE THREAD

**Issue by ParvalShieh** [HowCam/howcam.github.io#4]
> 已知圆内接四边形$ABCD$，对角线$AC,BD$交于点$P$。$\triangle{ABP}$的外接圆交$AC$于点$E$，$\triangle{CDP}$的外接圆交$AC$于点$F$。$\triangle{ABE}$，$\triangle{CDF}$的内心分别为点$I,J$，$IJ$交$AC$于点$K$。求证：$A,I,K,E$四点共圆。

is rendered to
![图片](https://github.com/HowCam/howcam.github.io/assets/79565670/7be7ce43-b11c-4764-b547-119a47802396)
on https://howcam.github.io/math/2017CMO-4/
Guess that it's cause by Mkdocs or PyMdown, but I failed to solve it.

**Comment by HowCam** [comment]
Actually, I also noticed this problem. Refreshing the page can solve this problem. This problem should be caused by the incomplete loading of the latex engine.
